-- Creates the database schema for the IAM services.
-- Audit columns (created_by, updated_by, deleted_by) are intentionally nullable to
-- support bootstrap scenarios before an authenticated principal is available.
-- Audit information is populated and managed by the application rather than the database.


-- Create enum for Principal Type
CREATE TYPE principal_type AS ENUM ('USER', 'CLIENT');

CREATE TABLE IF NOT EXISTS principal (
    id              BIGINT                        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            principal_type                NOT NULL,
    display_name    VARCHAR(100)                  NOT NULL,
    created_at      BIGINT                        NOT NULL,
    created_by      BIGINT,
    updated_at      BIGINT                        NOT NULL,
    updated_by      BIGINT,
    deleted_at      BIGINT,
    deleted_by      BIGINT,
    CONSTRAINT fk_principal_created_by FOREIGN KEY (created_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_principal_updated_by FOREIGN KEY (updated_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_principal_deleted_by FOREIGN KEY (deleted_by) REFERENCES principal (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "user" (
    id              BIGINT                        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(100)                  NOT NULL,
    password        VARCHAR(255)                  NOT NULL,
    active          BOOLEAN                       NOT NULL DEFAULT TRUE,
    created_by      BIGINT,
    created_at      BIGINT                        NOT NULL,
    updated_by      BIGINT,
    updated_at      BIGINT                        NOT NULL,
    deleted_by      BIGINT,
    deleted_at      BIGINT,
    principal_id    BIGINT                        NOT NULL,
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT uk_user_principal_id UNIQUE (principal_id),
    CONSTRAINT fk_user_principal_id FOREIGN KEY (principal_id) REFERENCES principal (id),
    CONSTRAINT fk_user_created_by FOREIGN KEY (created_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_user_updated_by FOREIGN KEY (updated_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_user_deleted_by FOREIGN KEY (deleted_by) REFERENCES principal (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "role" (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR(50)         NOT NULL,
    description     VARCHAR(100)        NOT NULL,
    created_by      BIGINT,
    created_at      BIGINT              NOT NULL,
    updated_by      BIGINT,
    updated_at      BIGINT              NOT NULL,
    deleted_by      BIGINT,
    deleted_at      BIGINT,
    CONSTRAINT uk_role_role_name UNIQUE (role_name),
    CONSTRAINT fk_role_created_by FOREIGN KEY (created_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_role_updated_by FOREIGN KEY (updated_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_role_deleted_by FOREIGN KEY (deleted_by) REFERENCES principal (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS permission (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name     VARCHAR(100)    NOT NULL,
    description         VARCHAR(200),
    CONSTRAINT uk_permission_permission_name UNIQUE (permission_name)
);

CREATE TABLE IF NOT EXISTS user_role (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT          NOT NULL,
    role_id             BIGINT          NOT NULL,
    created_by          BIGINT,
    created_at          BIGINT          NOT NULL,
    updated_by          BIGINT,
    updated_at          BIGINT          NOT NULL,
    deleted_by          BIGINT,
    deleted_at          BIGINT,
    CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role_id FOREIGN KEY (role_id) REFERENCES "role" (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_created_by FOREIGN KEY (created_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_user_role_updated_by FOREIGN KEY (updated_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_user_role_deleted_by FOREIGN KEY (deleted_by) REFERENCES principal (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS role_permission (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id             BIGINT          NOT NULL,
    permission_id       BIGINT          NOT NULL,
    created_by          BIGINT,
    created_at          BIGINT          NOT NULL,
    updated_by          BIGINT,
    updated_at          BIGINT          NOT NULL,
    deleted_by          BIGINT,
    deleted_at          BIGINT,
    CONSTRAINT fk_role_permission_role_id FOREIGN KEY (role_id) REFERENCES "role" (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission_id FOREIGN KEY (permission_id) REFERENCES "permission" (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_created_by FOREIGN KEY (created_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_role_permission_updated_by FOREIGN KEY (updated_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_role_permission_deleted_by FOREIGN KEY (deleted_by) REFERENCES principal (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(512)         NOT NULL,
    user_id         BIGINT              NOT NULL,
    expires_at      BIGINT              NOT NULL,
    created_at      BIGINT              NOT NULL,
    CONSTRAINT uk_refresh_token_user_id UNIQUE (user_id),
    CONSTRAINT fk_refresh_token_user_id FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS oauth_client (
    id                  BIGINT                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id           VARCHAR(100)            NOT NULL,
    client_secret       VARCHAR(255)            NOT NULL,
    scopes              VARCHAR(500)            NOT NULL,
    active              BOOLEAN                 NOT NULL DEFAULT TRUE,
    principal_id        BIGINT                  NOT NULL,
    created_by          BIGINT,
    created_at          BIGINT                  NOT NULL,
    updated_by          BIGINT,
    updated_at          BIGINT                  NOT NULL,
    deleted_by          BIGINT,
    deleted_at          BIGINT,

    CONSTRAINT uk_oauth_client_client_id UNIQUE (client_id),
    CONSTRAINT uk_oauth_client_principal_id UNIQUE (principal_id),
    CONSTRAINT fk_oauth_client_principal_id FOREIGN KEY (principal_id) REFERENCES principal (id),
    CONSTRAINT fk_oauth_client_created_by FOREIGN KEY (created_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_oauth_client_updated_by FOREIGN KEY (updated_by) REFERENCES principal (id) ON DELETE SET NULL,
    CONSTRAINT fk_oauth_client_deleted_by FOREIGN KEY (deleted_by) REFERENCES principal (id) ON DELETE SET NULL
);

-- Enforces uniqueness for active user-role/role-permission associations while allowing historical (soft-deleted) records.
CREATE UNIQUE INDEX uk_user_role_active ON user_role(user_id, role_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_role_permission_active ON role_permission(role_id, permission_id) WHERE deleted_at IS NULL;

-- Additional indexes to improve query performance on foreign key columns.
CREATE INDEX idx_user_role_user_id ON user_role(user_id);
CREATE INDEX idx_role_permission_permission_id ON role_permission(permission_id);